parameters:
#    settings_config.example.class: Settings\ConfigBundle\Example

services:
#    settings_config.example:
#        class: %settings_config.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
